### ISSUE TITLE
Write the _buyListing logic

### ISSUE THREAD

**Issue by marc-aurele-besner** [marc-aurele-besner/SimpleNft-MarketPlace#17]
## Write the _buyListing logic

- Make sure we receive the token using the safeTranferFrom or transferFrom (the full sell price)
- Send the sell amount - the fee to the seller
- Send the nft to the buyer
- Record the buyer address && timestamp in the mapping
- Make sure the listing is not already sold

**Comment by 0xenj** [comment]
done
