### ISSUE TITLE
add seller and buyer as argument to _createListing() and _buyListing()

### ISSUE THREAD

**Issue by marc-aurele-besner** [marc-aurele-besner/SimpleNft-MarketPlace#20]
## add seller and buyer as argument to _createListing() and _buyListing()

- add an address seller argument to _createListing to be used instead of msg.sender
- add a address buyer argument to _buyListing to be used instead of msg.sender

**Comment by 0xenj** [comment]
Done in pr "issue16" and issue"17-18"
