### ISSUE TITLE
Hook _createListing and _buyListing to the 4 external function

### ISSUE THREAD

**Issue by marc-aurele-besner** [marc-aurele-besner/SimpleNft-MarketPlace#21]
## Hook _createListing and _buyListing to the 4 external function

- For the 2 regular function, buyer and seller will be msg.sender
- For the 2 (by signature) function use the argument of the external function (don't worry about the r,s,v for now)

**Comment by 0xenj** [comment]
Done in existing pr "16" and "17-18"
