### ISSUE TITLE
Add arguments ListingCreated() and Sale()

### ISSUE THREAD

**Issue by marc-aurele-besner** [marc-aurele-besner/SimpleNft-MarketPlace#28]
## Add arguments ListingCreated() and Sale()

- Pass in listingId for both
- for create listing, seller, tokenContract, tokenId, salePrice
- for sale: seller

**Comment by 0xenj** [comment]
Je pense que vous vouliez dire buyer pour sale() et non seller

**Comment by 0xenj** [comment]
Done
