### ISSUE TITLE
Improve hardhat config with more network and settings

### ISSUE THREAD

**Issue by marc-aurele-besner** [marc-aurele-besner/SimpleNft-MarketPlace#3]
## Improve hardhat config with more network and settings

Taking inspiration from our precedent project

- Add dotenv dependency to the package
- Import dotenv in hardhat.config.js
- Add .env and .env.sample files
- Add more network, pass in the pk and rpcurl environment variable
- Add others settings in that file like etherscan API key and others

**Comment by 0xenj** [comment]
done
