### ISSUE TITLE
Add prettier dependencies

### ISSUE THREAD

**Issue by marc-aurele-besner** [marc-aurele-besner/SimpleNft-MarketPlace#6]
## Add prettier dependencies

- Add prettier and prettier-plugin-solidity ad devDependencies
- add .prettierrc file (take the same as our previous project)
- add .prettierignore file (take the same as our previous project)
- add .solcover.js file (take the same as our previous project)
- add CONTRIBUTING.md file (take the same as our previous project)

**Comment by 0xenj** [comment]
Done
