### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by marc-aurele-besner** [marc-aurele-besner/SimpleNft-MarketPlace#7]
## Improve Readme

The readme is the first page that anyone look at our repo or a fork of our repo see, so we should put more time on it, please do these improvements:

- Add warnings that this is a work in progress and for education purpose only (similar to what I recently added on our previous project)
- List all our functions in separate code box
- Add a licence badge at the top
- Add links to documentations
- Add a description of the projects
- Add others information as you see fit

**Comment by 0xenj** [comment]
done
